// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmrmqVwf03MDArXlWajQFmGGbx7dwSsnc',
    appId: '1:732668300858:web:b5a021ae748624ab79af03',
    messagingSenderId: '732668300858',
    projectId: 'tugaslab-dd2a4',
    authDomain: 'tugaslab-dd2a4.firebaseapp.com',
    storageBucket: 'tugaslab-dd2a4.firebasestorage.app',
    measurementId: 'G-Z9D4ZKCS2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhT61Z8CVT1Ri6zG97_yTHHOb9oUmOCM',
    appId: '1:732668300858:android:607db43af80953ee79af03',
    messagingSenderId: '732668300858',
    projectId: 'tugaslab-dd2a4',
    storageBucket: 'tugaslab-dd2a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnXAKa1ASZW0fhqodNnv80qifW5i_QH7U',
    appId: '1:732668300858:ios:764276ae74b18b9079af03',
    messagingSenderId: '732668300858',
    projectId: 'tugaslab-dd2a4',
    storageBucket: 'tugaslab-dd2a4.firebasestorage.app',
    iosBundleId: 'com.example.kostku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnXAKa1ASZW0fhqodNnv80qifW5i_QH7U',
    appId: '1:732668300858:ios:764276ae74b18b9079af03',
    messagingSenderId: '732668300858',
    projectId: 'tugaslab-dd2a4',
    storageBucket: 'tugaslab-dd2a4.firebasestorage.app',
    iosBundleId: 'com.example.kostku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmrmqVwf03MDArXlWajQFmGGbx7dwSsnc',
    appId: '1:732668300858:web:79dd69508d72e5f279af03',
    messagingSenderId: '732668300858',
    projectId: 'tugaslab-dd2a4',
    authDomain: 'tugaslab-dd2a4.firebaseapp.com',
    storageBucket: 'tugaslab-dd2a4.firebasestorage.app',
    measurementId: 'G-6GGV4TL2V7',
  );
}
